--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MegaHostings-Development-PocketMine/ServerSelector
build-by-default: true
branches:
- main
projects:
  ServerSelector:
    path: ""
...
